# Site
title: Hunet-DataInnovation
description: Stylish, Two-Column Jekyll Theme
url: https://Hunet-DataInnovation.github.io/
logo: halve.png                                       # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/unsplash-image-10.jpg             # this image will be shown on post list page
  default-post: images/unsplash-gallery-image-3.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
#email:             email
#google.plus:        hunet-datainnovation
twitter:            hunet-datainnovation
#facebook:           hunet-datainnovation
github:             hunet-datainnovation
#stackoverflow:     123456/hunet-datainnovation   from a "http://stackoverflow.com/users/123456/hunet-datainnovation" link
#linkedin:          hunet-datainnovation
#xing:              hunet-datainnovation
#instagram:          hunet-datainnovation
#lastfm:            hunet-datainnovation
#tumblr:            hunet-datainnovation
#pinterest:         hunet-datainnovation
#foursquare:        hunet-datainnovation
#steam:              hunet-datainnovation
#dribbble:          hunet-datainnovation
#youtube:           hunet-datainnovation
#soundcloud:        hunet-datainnovation
#weibo:             hunet-datainnovation
#flickr:            hunet-datainnovation
#codepen:           hunet-datainnovation
#keybase:           hunet-datainnovation
#xmpp:              hunet-datainnovation@server.com
#hackernews:        hunet-datainnovation
behance:           hunet-datainnovation

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
